#!/usr/bin/env python
import redis
import pyfeed

config = {
            'host': 'localhost',
            'port': 6379,
            'db': 0,
            'password': None,
        }

rdb = redis.Redis(config['host'], config['port'], config['db'],\
                              config['password'])
while True:
    try:
        r = rdb.brpop('updatejob', 0)
        pyfeed.startpoint()
    except:
        print("Oops")

